Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  DisabledByDefault: true
